version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hermes_db
    restart: always
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hermes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tor:
    image: osminogin/tor-simple
    container_name: hermes_tor
    restart: always
    environment:
      - TOR_CONTROL_PORT=9051
      - TOR_CONTROL_PASS=
    ports:
      - "9050:9050"
      - "9051:9051"
    command: tor --ControlPort 0.0.0.0:9051 --AllowDotExit 1 --SocksPort 0.0.0.0:9050 --CookieAuthentication 0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hermes_app
    environment:
      DATABASE_URL: "postgresql+asyncpg://hermes:pass@db:5432/hermes_db"
      PYTHONPATH: "/src"
    depends_on:
      - tor
      - db
    stdin_open: true
    tty: true

volumes:
  pgdata: