version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hermes_db
    restart: always
    environment:
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hermes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hermes_app
    environment:
      DATABASE_URL: "postgresql+asyncpg://hermes:pass@db:5432/hermes_db"
      PYTHONPATH: "/src"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  pgdata: